# Generated by Django 5.2.17 on 2026-08-19 12:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_tenant_email_case_insensitive'),
        ),
    ]
